✨ feat: Profile 생성 서비스 구현 및 BaseReponse, BaseStatusCode 추가
Spoon-Lab/OurJourney-BE pull request #11
Opened 2024-08-31 09:02 UTC by chaerish

## 📝 제목
✨ feat: Profile 생성 서비스 구현 및 BaseReponse, BaseStatusCode 추가
  
## ✨ 작업 내용
- `BaseReponse`생성: 앞으로 Controller에서 ResponseEntity가 아닌, 커스텀한 BaseReponse를 사용할 예정입니다.
- `ProfileRequestDto` 생성: 장고에서 Profile 생성을 위해 스프링으로 넘겨주는 Dto객체를 담습니다.
- `ProfileService` 생성 및 `createProfile()` 메서드 생성 : ProfileRequestDto에 담겨온 필드를 토대로 새로운 - Profile 객체를 생성하는 로직을 추가했습니다.
- `BaseStatusCode`,` ErrorCode`,`SuccessCode` 생성: 응답 Status Code 와 메세지 enum 을 생성했습니다.
  
## 💁‍♀️ 참고 사항
- [AccessLevel.PROTECTED 에 대해 자세히]( https://velog.io/@kevin_/%EB%82%B4%EA%B0%80-NoargsConstructor-access-AccessLevel.PROTECTED%EB%A5%BC-%EC%99%9C-%EC%9E%91%EC%84%B1%ED%96%88%EC%9D%84%EA%B9%8C) 어노테이션 쓸 때 진중하게 쓰기 위해서 (?) 참고했습니다!

  
## 🤔 논의 사항
- `ProfileRequestDto` 의 변수 이름을 장고와 통일시켜야 할 것 같습니다. 지금 제가 임의로 지어놨습니다!
- 혹은 알려주시면 Property에 지정하겠습니다! 
- 앞으로 ErrorCode는 좀 더 자세하게 정의할 예정입니다.

  
## 🔧 앞으로의 과제

  
## 🚨 관련 이슈
- https://github.com/Spoon-Lab/OurJourney-BE/issues/10

2024-08-31 15:35 UTC, blingblin-g requested changes

2024-08-31 15:35 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
> +        Profile profile = ProfileRequestDto.toEntity(profileRequestDto);
자기 자신을 넣는 이유가 있을까요? 
static method로 할 이유가 있나요? 
`profileRequestDto.toEntity()` 이런 식으로 instance method를 쓰는 건 어떨까요?

2024-08-31 15:35 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/common/ErrorCode.java
> +    METHOD_NOT_ALLOWED(405,"Method is not allowed.");
스프링 프레임워크에서 제공하는 `org.springframework.http.HttpStatus`를 쓰지 않는 이유가 있을까요?

2024-08-31 15:41 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileRequestDto.java
> +    String nickName;//닉네임
프로필 닉네임은 장고가 내려주는 게 아니라 자바서버에서 관리하게 될 것 같고, 장고에서는 `id` 정도만 내려주게 될 것 같아요. user_id가 조금 더 좋다면, 그렇게 해도 될 것 같아요.

그리고 장고가 요청을 하는 게 아니라, 자바 서버가 요청을 하게 될텐데, 이름이 requestDto인 이유를 잘 모르겠어요.

2024-09-01 04:37 UTC, closed without merging

2024-09-01 04:53 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
> +        Profile profile = ProfileRequestDto.toEntity(profileRequestDto);
[이 링크](https://velog.io/@bluesun147/of-from-%EB%A9%94%EC%84%9C%EB%93%9C-%ED%8C%A8%ED%84%B4) 참고해서 만들었는데 뭔가 Entity나 서비스에 위임하는 것보다는 dto스스로가 처리하는 게 좋을 것 같다고 판단해서 만들었습니다!
그런데 제 생각에도 toEntity() 는 굳이 static으로 하지 않아도 될 것 같네요!!! to Entity()는 수정하겠습니닷 
- [toEntity() 메서드에 대해](https://velog.io/@smc2315/DTO-Entity-%EB%B3%80%ED%99%98-%EB%A9%94%EC%84%9C%EB%93%9C-%EA%B5%AC%ED%98%84-%EC%9C%84%EC%B9%98%EB%8A%94-%EC%96%B4%EB%94%94%EA%B0%80-%EC%A2%8B%EC%9D%84%EA%B9%8C)

2024-09-01 04:56 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/common/ErrorCode.java
> +    METHOD_NOT_ALLOWED(405,"Method is not allowed.");
고치겠습니다!!!

2024-09-01 04:56 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileRequestDto.java
> +    String nickName;//닉네임
이 부분도 수정하겠습니다!