Feature/profile service and dto
Spoon-Lab/OurJourney-BE pull request #13
Opened 2024-08-31 09:58 UTC by chaerish

## 📝 제목
✨ feat: Profile 수정, 보기 서비스 구현 및 ProfileDto 생성
 
  
## ✨ 작업 내용

- ProfileResponseDto 생성 : 프로필 정보를 응답해주기 위한 dto를 생성했습니다.
- ProfileEditRequestDto 생성 : 프로필 수정을 담을 dto를 생성했습니다.
- getMyProfile() 생성: 내 프로필을 보기 위한 메서드를 생성했습니다.
- putMyProfile() 생성: 내 프로필을 수정할 수 있는 메서드를 생성했습니다.
  
  
## 💁‍♀️ 참고 사항
- [dto를 entity로 변경하는 메서드 이름에 대해](https://velog.io/@bluesun147/of-from-%EB%A9%94%EC%84%9C%EB%93%9C-%ED%8C%A8%ED%84%B4) 

  
## 🤔 논의 사항
1. 프로필 수정할 때 프로필 아이디를 가지고 수정을 요청하려는 생각을 했는데 (스프링은 토큰이 없으니가) 생각해보니 본인 건지 인증할 방법이 업슴.
    - 혹시 프로필 수정할 때도 장고 → 스프링을 통해서 유저 pk를 내려주시는지?..
    - 이런 형태이면 댓글이나 글 로직 짤 때도 2중으로 거쳐야합니다.
2. s3 를 장고쪽에서 관리한다고 하셨는데, 제 생각에는 글 작성 시 사진 첨부 + 프로필 사진 변경에 있어서 스프링이 관리해야할 것 같습니다. 
    - 제가 생각했던 로직은 소셜 로그인 후에 프로필 쪽의 닉네임이나 자기소개, 이미지는 null로 기본 생성(디폴트)되며 나중에 수정할 때 채워넣는걸로 하는게 좋을 것 같아서요.. .
  
## 🔧 앞으로의 과제
- ErrorHandler 만들기.
- 나머지 Profile 객체에 대한 남은 로직 만들기.
  
## 🚨 관련 이슈
- https://github.com/Spoon-Lab/OurJourney-BE/issues/12

2024-08-31 15:46 UTC, blingblin-g commented
1. 인증/인가에 관한 로직은 전부 인증서버(장고)를 거쳐야 합니다. 수정할 때도, 자기 자신인지 확인하기 위해 인증 서버를 거치게 됩니다.
2. s3에 이미지를 올리는 API는 장고에서 만듭니다. 이미지를 받아서 url을 내려주면, 클라이언트가 이미지 url을 자바 서버로 보내게 됩니다. 자바서버는 이미지 url만 올리면 됩니다.

2024-08-31 15:50 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileEditRequestDto.java
> +public class ProfileRequestDto { //todo: 장고와 변수 이름을 맞출 필요가 있습니다.
클래스명이랑 파일명이 달라요

2024-08-31 15:53 UTC, blingblin-g requested changes
파일명이랑 클래스명을 맞춰주세요
그리고 fork 떠서 하시는 이유가 있을까요?
특별한 이유가 없다면 레포를 바로 클론해서 작업해주세요

2024-09-01 04:32 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileEditRequestDto.java
> +public class ProfileRequestDto { //todo: 장고와 변수 이름을 맞출 필요가 있습니다.
고치겠습니다!

2024-09-01 04:37 UTC, closed without merging

2024-09-01 04:50 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileEditRequestDto.java
> +public class ProfileRequestDto { //todo: 장고와 변수 이름을 맞출 필요가 있습니다.
고쳤습니다!

2024-09-01 04:50 UTC, chaerish commented
> 파일명이랑 클래스명을 맞춰주세요 그리고 fork 떠서 하시는 이유가 있을까요? 특별한 이유가 없다면 레포를 바로 클론해서 작업해주세요

메인 클론해서 다시 작업하겠습니다!