✨ feat: Post,tag,like-entity 생성
Spoon-Lab/OurJourney-BE pull request #16
Opened 2024-09-02 07:21 UTC by chaerish

## 📝 제목
✨ feat: Post,tag,like-entity 생성
  

## ✨ 작업 내용
`Post` - 게시글
`Tag` - 해시태그
`Like`- 좋아요
과 관련된 엔티티들을 생성했습니다.
  
- Post-Tag: @ManyToMany 관계로 중간 테이블 PostTag 중간 테이블을 생성했습니다.
- Post-Like: @ManyToMany 관계로 중간 테이블 PostLike 중간 테이블을 생성했습니다.
## 💁‍♀️ 참고 사항
- [다대다 중간테이블 참고](https://velog.io/@jadenkim5179/%EC%A4%91%EA%B0%84-%ED%85%8C%EC%9D%B4%EB%B8%94%EB%A1%9C-%EC%9D%B4%EC%A4%91-%EA%B4%80%EA%B3%84-%ED%92%80%EC%96%B4%EB%82%B4%EA%B8%B0)

  
## 🤔 논의 사항
- Profile을 넘겨줄 때 좋아요 한 글을 볼 수 있게 하려면 Profile과 PostLike의 관계도 지정해주어야 할까요?
- 제가 잘 도메인을 설계한지도 궁금합니다. 피드백 해주세요!

  
## 🔧 앞으로의 과제
- 글 CRUD 완성하기

  
## 🚨 관련 이슈
https://github.com/Spoon-Lab/OurJourney-BE/issues/15

2024-09-02 14:38 UTC, blingblin-g requested changes
고생하셨습니다. [API문서](https://www.notion.so/chaerish/API-Docs-for-BE-14b387a3301a4f3a851b5a4dddc14bb7?pvs=4) 한 번 확인해보시고, 궁금한 거 있으면 말씀 주세요. 
ERD를 먼저 그려보고 테이블을 작성하는 것을 추천드립니다. https://dbdiagram.io/home

2024-09-02 14:38 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/Like.java
> +}
이 Like는 어떤 용도인지 궁금하네요

2024-09-02 14:38 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/Post.java
> +    List<PostLike> postLikes;
기획 상 글과 타래가 따로 분리 돼있는데, 글이 Post인가요?

postCategory는 어드민에서 추가 삭제될 리소스라서, enum보다는 테이블을 따로 만드는 게 좋을 것 같아요. 다만 지금 당장 필요하진 않기 때문에 일단 이대로 가고, 나중에 DB를 변경하는 방향이 효율적일 것 같습니다.

tag는 M2M이 더 적합한 것 같아요. 더 나은 방향이 있다면 얘기해주세요.

2024-09-02 14:38 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/PostLike.java
> +    Like like;
like에 tag_id가 달려있는데, 잘못 달려있는 것처럼 보이네요.
글과 좋아요 누른 사람을 연결하는 테이블이 된다면, profile_id가 필요할 것 같아요.

2024-09-02 14:38 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/Tag.java
> +    List<PostLike> postLikes;
혹시 잘못 넣으신걸까요? Like랑 어떤 관계인지 궁금하네요.

2024-09-03 09:10 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
> +import pudding.toy.ourJourney.dto.django.ProfileAuthResponseDto;
오 그런 점은 미쳐 생각하지 못했네요. 패키지 이름 수정하겠습니다!

2024-09-03 09:10 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/Like.java
> +}
앗 이 Like는 좋아요에요. 좋아요랑 post(글) 이 다대다라고 생각해서 일단 만들어보았습니다.. 나중에 좋아요 수같은것도 집계하려면 다대다 중간테이블 양방향이 가장 좋을 것 같아서 구현했습니다

2024-09-03 09:11 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/Post.java
> +    List<PostLike> postLikes;
글이 Post입니다. 타래는 Thread 입니다. 현재 tag는 manyTomany로 해서 중간 테이블을 생성했습니다!

2024-09-03 09:13 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/Tag.java
> +    List<PostLike> postLikes;
헉 이 부분은 수정하도록 하겠습니다.

2024-09-03 09:14 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileEditRequestDto.java
>      int id; //user pk
앗 제가 서치해봤는데 장고의 기본 pk가 int 값으로 한다고 한걸 봐서 그렇게 한 것 같아요. 혹시 타입 변환이 된다면 그냥 Long으로 수정하겠습니다!

2024-09-03 12:19 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/Like.java
> +}
Like에 별다른 정보가 없어서 불필요한 테이블인 것 같아요. 
보다 명확하게 ERD를 한 번 그려보는 건 어떨까요.
간단하게 Profile - Like - Post 이런 느낌일 것 같네요.

2024-09-03 12:34 UTC, chaerish commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/Like.java
> +}
> Like에 별다른 정보가 없어서 불필요한 테이블인 것 같아요. 보다 명확하게 ERD를 한 번 그려보는 건 어떨까요. 간단하게 Profile - Like - Post 이런 느낌일 것 같네요.

넵 지금 erd cloud 파서 그려보는 중입니다! 노션에 메일 주시면 초대드릴게요

2024-09-05 10:40 UTC, blingblin-g commented on ourJourney/src/main/java/pudding/toy/ourJourney/entity/PostLike.java
> +    Profile profile;
제가 잘 몰라서 그러는데 `@JoinColumn` 뒤에 한 칸 띄워도 상관 없나용?

2024-09-05 10:43 UTC, blingblin-g approved these changes
고생 많으셨습니다! 👍

2024-09-05 10:43 UTC, merged